"""Add created_by and modified_by to Book model

Revision ID: a55b7eebe311
Revises: 707f31ce89f7
Create Date: 2024-10-04 09:18:10.082971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55b7eebe311'
down_revision = '707f31ce89f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('modified_by', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('modified_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
